blueprint:
  name: Bambu printer – finish / fault notify with snapshot (simplified)
  description: >
    Sends a Home Assistant mobile notification with a camera snapshot when a
    Bambu printer finishes or faults. Auto-discovers sensors based on device prefix.
    Just select your printer device and configure a few options!
  domain: automation

  input:
    printer_device:
      name: Bambu Printer Device
      description: Select your Bambu printer device (sensors will be auto-discovered)
      selector:
        device:
          integration: bambu_lab
          multiple: false

    notifications_enabled_boolean:
      name: Notifications enabled boolean
      description: input_boolean that must be ON to send notifications.
      selector:
        entity:
          domain: input_boolean

    notify_device:
      name: Notify device/service
      description: "Enter notify service name (e.g., mobile_app_your_phone) or leave empty to disable mobile notifications."
      default: ""
      selector:
        text:

    critical_start:
      name: Critical fault start time
      description: Time from which fault notifications become critical.
      default: "07:00:00"
      selector:
        time: {}

    critical_end:
      name: Critical fault end time
      description: Time after which faults are no longer critical.
      default: "21:00:00"
      selector:
        time: {}

    cooldown_minutes:
      name: Cooldown between alerts (minutes)
      description: Minimum time between any alerts from this automation.
      default: 5
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: min
          mode: slider

    snapshot_delay_seconds:
      name: Snapshot delay (seconds)
      description: Delay before taking snapshot (negative = earlier, positive = later). Use -5 to -10 for finish photos before bed drops.
      default: 0
      selector:
        number:
          min: -30
          max: 30
          unit_of_measurement: s
          mode: slider

    progress_trigger_threshold:
      name: Progress trigger threshold (%)
      description: Trigger snapshot at this progress % (e.g., 99 to capture before bed drops). Leave at 0 to use state changes only.
      default: 0
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

    printers_view_uri:
      name: Printers view URI (optional)
      description: Lovelace path, e.g. /lovelace/3d_printers (leave blank to disable action button).
      default: ""
      selector:
        text: {}

mode: single

variables:
  printer_device: !input printer_device
  
  # Get all entities for this device
  device_entities: "{{ device_entities(printer_device) }}"
  
  # Auto-discover sensor entities
  print_status_sensor: "{{ device_entities | select('search', 'sensor.*_print_status$') | list | first }}"
  print_error_binary: "{{ device_entities | select('search', 'binary_sensor.*_print_error$') | list | first }}"
  current_stage_sensor: "{{ device_entities | select('search', 'sensor.*_current_stage$') | list | first }}"
  progress_sensor: "{{ device_entities | select('search', 'sensor.*_print_progress$') | list | first }}"
  printer_name_sensor: "{{ device_entities | select('search', 'sensor.*_printer_name$') | list | first }}"
  task_name_sensor: "{{ device_entities | select('search', 'sensor.*_task_name$') | list | first }}"
  print_weight_sensor: "{{ device_entities | select('search', 'sensor.*_print_weight$') | list | first }}"
  camera_entity: "{{ device_entities | select('search', 'camera.*_camera$') | list | first }}"
  
  notifications_enabled_boolean: !input notifications_enabled_boolean
  notify_device: !input notify_device
  critical_start: !input critical_start
  critical_end: !input critical_end
  cooldown_minutes: !input cooldown_minutes
  snapshot_delay_seconds: !input snapshot_delay_seconds
  progress_trigger_threshold: !input progress_trigger_threshold
  printers_view_uri: !input printers_view_uri

  printer_name: "{{ states(printer_name_sensor) }}"
  task_name: "{{ states(task_name_sensor) }}"
  print_weight: "{{ states(print_weight_sensor) }}"
  status: "{{ states(print_status_sensor) }}"
  progress: "{{ states(progress_sensor) | int(0) }}"
  current_stage: "{{ states(current_stage_sensor) }}"
  
  snapshot_file: "/config/www/snapshots/bambu_{{ printer_name | lower | replace(' ', '_') }}.jpg"
  snapshot_url: "/local/snapshots/bambu_{{ printer_name | lower | replace(' ', '_') }}.jpg"

trigger:
  # Early snapshot trigger - fires when progress reaches threshold
  - platform: template
    id: progress_threshold
    value_template: >
      {% set entities = device_entities(printer_device) %}
      {% set progress_entity = entities | select('search', 'sensor.*_print_progress$') | list | first %}
      {% set threshold = progress_trigger_threshold | int %}
      {{ threshold > 0 and states(progress_entity) | int(0) >= threshold }}

  - platform: template
    id: finish
    value_template: >
      {% set entities = device_entities(printer_device) %}
      {% set status_entity = entities | select('search', 'sensor.*_print_status$') | list | first %}
      {{ states(status_entity) == 'finish' }}

  - platform: template
    id: failed_status
    value_template: >
      {% set entities = device_entities(printer_device) %}
      {% set status_entity = entities | select('search', 'sensor.*_print_status$') | list | first %}
      {{ states(status_entity) == 'failed' }}

  - platform: template
    id: error_flag
    value_template: >
      {% set entities = device_entities(printer_device) %}
      {% set error_entity = entities | select('search', 'binary_sensor.*_print_error$') | list | first %}
      {{ is_state(error_entity, 'on') }}

condition:
  # Check if notifications are enabled
  - condition: state
    entity_id: !input notifications_enabled_boolean
    state: "on"

  # Check if essential sensors are available
  - condition: template
    value_template: >
      {{ not is_state(printer_name_sensor, 'unavailable') and
         not is_state(printer_name_sensor, 'unknown') and
         not is_state(print_status_sensor, 'unavailable') and
         not is_state(print_status_sensor, 'unknown') }}

  # Cooldown check using automation's last_triggered attribute
  - condition: template
    value_template: >
      {% set last = state_attr('automation.' ~ this.object_id, 'last_triggered') %}
      {% if last == none %}
        true
      {% else %}
        {% set last_ts = as_timestamp(last) %}
        {% set diff = as_timestamp(now()) - last_ts %}
        {{ diff > 60 * (cooldown_minutes | int) }}
      {% endif %}

  # Stage and progress guard (less restrictive to catch more fault scenarios)
  - condition: template
    value_template: >
      {{ progress > 0 or 
         current_stage in [
           'printing',
           'inspecting_first_layer',
           'auto_bed_leveling',
           'paused'
         ] }}

action:
  # Take snapshot with configurable delay (can be negative for earlier capture)
  - delay:
      seconds: "{{ snapshot_delay_seconds | int }}"
    continue_on_error: true

  - service: camera.snapshot
    target:
      entity_id: "{{ camera_entity }}"
    data:
      filename: "{{ snapshot_file }}"
    continue_on_error: true

  # Wait for actual finish/fault state if triggered by progress threshold
  - if:
      - condition: template
        value_template: "{{ trigger.id == 'progress_threshold' }}"
    then:
      - wait_template: >
          {% set entities = device_entities(printer_device) %}
          {% set status_entity = entities | select('search', 'sensor.*_print_status$') | list | first %}
          {% set error_entity = entities | select('search', 'binary_sensor.*_print_error$') | list | first %}
          {{ is_state(status_entity, 'finish') or is_state(status_entity, 'failed') or is_state(error_entity, 'on') }}
        timeout:
          minutes: 10
        continue_on_timeout: false

  - delay: "00:00:02"

  # Calculate notification properties
  - variables:
      is_fault: >
        {{ is_state(print_status_sensor, 'failed') or 
           is_state(print_error_binary, 'on') }}
      is_critical_time: >
        {% if not is_fault %}
          false
        {% else %}
          {% set now_time = now().time() %}
          {% set start = strptime(critical_start, '%H:%M:%S').time() %}
          {% set end = strptime(critical_end, '%H:%M:%S').time() %}
          {{ now_time >= start and now_time <= end }}
        {% endif %}
      notification_title: >
        {% if is_fault %}
          {{ printer_name }} FAULT{{ ' (CRITICAL)' if is_critical_time else '' }}
        {% else %}
          {{ printer_name }} print finished
        {% endif %}
      notification_message: >
        {% if is_fault %}
          ❌ {{ task_name or 'Print job' }} FAILED on {{ printer_name }}.
          Status: {{ status }}, progress {{ progress }}%.
        {% else %}
          ✅ {{ task_name or 'Print job' }} finished on {{ printer_name }}.
          Weight {{ print_weight }} g, {{ progress }}% reported.
        {% endif %}

  # Send mobile notification (if device configured)
  - if:
      - condition: template
        value_template: "{{ notify_device != '' }}"
    then:
      - service: "notify.{{ notify_device }}"
        data:
          title: "{{ notification_title }}"
          message: "{{ notification_message }}"
          data:
            image: "{{ snapshot_url }}"
            tag: "bambu_print_{{ printer_name }}"
            sticky: true
            persistent: true
            push: >
              {% if is_critical_time %}
              {{ {'sound': {'name': 'default', 'critical': 1, 'volume': 1.0}} }}
              {% endif %}
            actions: >
              {% if printers_view_uri != '' %}
              [{"action": "OPEN_PRINTER_VIEW", "title": "Open printers view", "uri": "{{ printers_view_uri }}"}]
              {% else %}
              []
              {% endif %}

  # Create persistent notification for faults only
  - if:
      - condition: template
        value_template: "{{ is_fault }}"
    then:
      - service: persistent_notification.create
        data:
          title: "{{ printer_name }} fault"
          message: >
            {{ task_name or 'Print job' }} on {{ printer_name }} has a fault.
            Status: {{ status }}, progress {{ progress }}%.
          notification_id: "bambu_fault_{{ printer_name }}"
