blueprint:
  name: Bambu printer – finish / fault notify with snapshot (improved)
  description: >
    Sends a Home Assistant mobile notification with a camera snapshot when a
    Bambu printer finishes or faults. Includes critical sound window, cooldown,
    stage/progress guards, persistent notification, and a per-printer
    enable switch. Improved with better error handling, consolidated logic,
    and proper cooldown tracking.
  domain: automation

  input:
    print_status_sensor:
      name: Print status sensor
      description: Sensor with states like running / finish / failed.
      selector:
        entity:
          domain: sensor

    print_error_binary:
      name: Print error binary sensor
      description: Binary sensor that goes ON on print error.
      selector:
        entity:
          domain: binary_sensor

    current_stage_sensor:
      name: Current stage sensor
      description: Enum sensor for printer stage (printing, inspecting_first_layer, etc.).
      selector:
        entity:
          domain: sensor

    progress_sensor:
      name: Progress sensor
      description: Sensor for print progress (%).
      selector:
        entity:
          domain: sensor

    printer_name_sensor:
      name: Printer name sensor
      description: Sensor with the printer name (e.g. R2D7).
      selector:
        entity:
          domain: sensor

    task_name_sensor:
      name: Task name sensor
      description: Sensor with current task/job name.
      selector:
        entity:
          domain: sensor

    print_weight_sensor:
      name: Print weight sensor
      description: Sensor with print weight in grams.
      selector:
        entity:
          domain: sensor

    camera:
      name: Printer camera
      selector:
        entity:
          domain: camera

    notifications_enabled_boolean:
      name: Notifications enabled boolean
      description: input_boolean that must be ON to send notifications.
      selector:
        entity:
          domain: input_boolean



    notify_device:
      name: Notify device/service
      description: "Device or service name (e.g. mobile_app_your_phone). Leave empty to disable notifications."
      default: ""
      selector:
        text: {}

    critical_start:
      name: Critical fault start time
      description: Time from which fault notifications become critical.
      default: "07:00:00"
      selector:
        time: {}

    critical_end:
      name: Critical fault end time
      description: Time after which faults are no longer critical.
      default: "21:00:00"
      selector:
        time: {}

    cooldown_minutes:
      name: Cooldown between alerts (minutes)
      description: Minimum time between any alerts from this automation.
      default: 5
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: min
          mode: slider

    snapshot_delay_seconds:
      name: Snapshot delay (seconds)
      description: Delay before taking snapshot (negative = earlier, positive = later). Use -5 to -10 for finish photos before bed drops.
      default: 0
      selector:
        number:
          min: -30
          max: 30
          unit_of_measurement: s
          mode: slider

mode: single

variables:
  print_status_sensor: !input print_status_sensor
  print_error_binary: !input print_error_binary
  current_stage_sensor: !input current_stage_sensor
  progress_sensor: !input progress_sensor
  printer_name_sensor: !input printer_name_sensor
  task_name_sensor: !input task_name_sensor
  print_weight_sensor: !input print_weight_sensor
  camera_entity: !input camera
  notifications_enabled_boolean: !input notifications_enabled_boolean

  notify_device: !input notify_device
  snapshot_file: "/config/www/snapshots/bambu_{{ printer_name | lower | replace(' ', '_') }}.jpg"
  snapshot_url: "/local/snapshots/bambu_{{ printer_name | lower | replace(' ', '_') }}.jpg"
  critical_start: !input critical_start
  critical_end: !input critical_end
  cooldown_minutes: !input cooldown_minutes
  printers_view_uri: !input printers_view_uri

  printer_name: "{{ states(printer_name_sensor) }}"
  task_name: "{{ states(task_name_sensor) }}"
  print_weight: "{{ states(print_weight_sensor) }}"
  status: "{{ states(print_status_sensor) }}"
  progress: "{{ states(progress_sensor) | int(0) }}"
  current_stage: "{{ states(current_stage_sensor) }}"

trigger:
  - platform: state
    id: finish
    entity_id: !input print_status_sensor
    from: "running"
    to: "finish"

  - platform: state
    id: failed_status
    entity_id: !input print_status_sensor
    from:
      - "running"
      - "prepare"
    to: "failed"

  - platform: state
    id: error_flag
    entity_id: !input print_error_binary
    from: "off"
    to: "on"

condition:
  # Check if notifications are enabled
  - condition: state
    entity_id: !input notifications_enabled_boolean
    state: "on"

  # Check if essential sensors are available
  - condition: template
    value_template: >
      {{ not is_state(printer_name_sensor, 'unavailable') and
         not is_state(printer_name_sensor, 'unknown') and
         not is_state(print_status_sensor, 'unavailable') and
         not is_state(print_status_sensor, 'unknown') }}

  # Cooldown check using automation's last_triggered attribute
  - condition: template
    value_template: >
      {% set last = state_attr('automation.' ~ this.object_id, 'last_triggered') %}
      {% if last == none %}
        true
      {% else %}
        {% set last_ts = as_timestamp(last) %}
        {% set diff = as_timestamp(now()) - last_ts %}
        {{ diff > 60 * (cooldown_minutes | int) }}
      {% endif %}

  # Stage and progress guard (less restrictive to catch more fault scenarios)
  - condition: template
    value_template: >
      {{ progress > 0 or 
         current_stage in [
           'printing',
           'inspecting_first_layer',
           'auto_bed_leveling',
           'paused'
         ] }}

action:
  # Take snapshot with error handling
  - service: camera.snapshot
    target:
      entity_id: "{{ camera_entity }}"
    data:
      filename: "{{ snapshot_file }}"
    continue_on_error: true

  - delay: "00:00:02"

  # Calculate notification properties
  - variables:
      is_fault: >
        {{ is_state(print_status_sensor, 'failed') or 
           is_state(print_error_binary, 'on') }}
      is_critical_time: >
        {% if not is_fault %}
          false
        {% else %}
          {% set now_time = now().time() %}
          {% set start = strptime(critical_start, '%H:%M:%S').time() %}
          {% set end = strptime(critical_end, '%H:%M:%S').time() %}
          {{ now_time >= start and now_time <= end }}
        {% endif %}
      notification_title: >
        {% if is_fault %}
          {{ printer_name }} FAULT{{ ' (CRITICAL)' if is_critical_time else '' }}
        {% else %}
          {{ printer_name }} print finished
        {% endif %}
      notification_message: >
        {% if is_fault %}
          ❌ {{ task_name or 'Print job' }} FAILED on {{ printer_name }}.
          Status: {{ status }}, progress {{ progress }}%.
        {% else %}
          ✅ {{ task_name or 'Print job' }} finished on {{ printer_name }}.
          Weight {{ print_weight }} g, {{ progress }}% reported.
        {% endif %}

  # Send mobile notification (if device configured)
  - if:
      - condition: template
        value_template: "{{ notify_device != '' }}"
    then:
      - service: "notify.{{ notify_device }}"
        data:
          title: "{{ notification_title }}"
          message: "{{ notification_message }}"
          data:
            image: "{{ snapshot_url }}"
            tag: "bambu_print_{{ printer_name }}"
            sticky: true
            persistent: true
            push: >
              {% if is_critical_time %}
              {{ {'sound': {'name': 'default', 'critical': 1, 'volume': 1.0}} }}
              {% endif %}
            actions: >
              {% if printers_view_uri != '' %}
              [{"action": "OPEN_PRINTER_VIEW", "title": "Open printers view", "uri": "{{ printers_view_uri }}"}]
              {% else %}
              []
              {% endif %}

  # Create persistent notification for faults only
  - if:
      - condition: template
        value_template: "{{ is_fault }}"
    then:
      - service: persistent_notification.create
        data:
          title: "{{ printer_name }} fault"
          message: >
            {{ task_name or 'Print job' }} on {{ printer_name }} has a fault.
            Status: {{ status }}, progress {{ progress }}%.
          notification_id: "bambu_fault_{{ printer_name }}"
