blueprint:
  name: Bambu printer – finish / fault notify with snapshot (improved)
  description: >
    Sends a Home Assistant mobile notification with a camera snapshot when a
    Bambu printer finishes or faults. Includes critical sound window, cooldown,
    stage/progress guards, persistent notification, and a per-printer
    enable switch. Improved with consolidated logic and better error handling.
  domain: automation

  input:
    print_status_sensor:
      name: Print status sensor
      description: Sensor with states like running / finish / failed.
      selector:
        entity:
          domain: sensor

    print_error_binary:
      name: Print error binary sensor
      description: Binary sensor that goes ON on print error.
      selector:
        entity:
          domain: binary_sensor

    current_stage_sensor:
      name: Current stage sensor
      description: Enum sensor for printer stage (printing, inspecting_first_layer, etc.).
      selector:
        entity:
          domain: sensor

    progress_sensor:
      name: Progress sensor
      description: Sensor for print progress (%).
      selector:
        entity:
          domain: sensor

    printer_name_sensor:
      name: Printer name sensor
      description: Sensor with the printer name (e.g. R2D7).
      selector:
        entity:
          domain: sensor

    task_name_sensor:
      name: Task name sensor
      description: Sensor with current task/job name.
      selector:
        entity:
          domain: sensor

    print_weight_sensor:
      name: Print weight sensor
      description: Sensor with print weight in grams.
      selector:
        entity:
          domain: sensor

    camera:
      name: Printer camera
      selector:
        entity:
          domain: camera

    notifications_enabled_boolean:
      name: Notifications enabled boolean
      description: input_boolean that must be ON to send notifications.
      selector:
        entity:
          domain: input_boolean

    notify_device:
      name: Notify device/service
      description: "Enter notify service name (e.g., mobile_app_your_phone) or leave empty to disable mobile notifications."
      default: ""
      selector:
        text:

    success_notification_type:
      name: Success notification type
      description: Notification priority for successful prints.
      default: "normal"
      selector:
        select:
          options:
            - label: "Normal (regular notification)"
              value: "normal"
            - label: "Critical (bypass Do Not Disturb)"
              value: "critical"

    success_critical_start:
      name: Success critical start time
      description: Time from which success notifications become critical (only if type is Critical).
      default: "00:00:00"
      selector:
        time: {}

    success_critical_end:
      name: Success critical end time
      description: Time after which success notifications are no longer critical.
      default: "23:59:59"
      selector:
        time: {}

    fault_notification_type:
      name: Fault notification type
      description: Notification priority for failed prints.
      default: "critical"
      selector:
        select:
          options:
            - label: "Normal (regular notification)"
              value: "normal"
            - label: "Critical (bypass Do Not Disturb)"
              value: "critical"

    fault_critical_start:
      name: Fault critical start time
      description: Time from which fault notifications become critical (only if type is Critical).
      default: "07:00:00"
      selector:
        time: {}

    fault_critical_end:
      name: Fault critical end time
      description: Time after which fault notifications are no longer critical.
      default: "21:00:00"
      selector:
        time: {}

    critical_sound:
      name: Critical alert sound
      description: Sound name for critical fault alerts (iOS). Common options - default, alert, bell, chime, glass, horn, etc.
      default: "default"
      selector:
        text:

    critical_volume:
      name: Critical alert volume
      description: Volume for critical fault alerts (0.0 to 1.0).
      default: 1.0
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1
          mode: slider

    cooldown_minutes:
      name: Cooldown between alerts (minutes)
      description: Minimum time between any alerts from this automation.
      default: 5
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: min
          mode: slider

    progress_trigger_threshold:
      name: Progress trigger threshold (%)
      description: Trigger snapshot at this progress % (recommended 98-99 to capture before bed drops).
      default: 99
      selector:
        number:
          min: 95
          max: 100
          unit_of_measurement: "%"
          mode: slider

    printers_view_uri:
      name: Printers view URI (optional)
      description: Lovelace path, e.g. /lovelace/3d_printers (leave blank to disable action button).
      default: ""
      selector:
        text: {}

mode: queued
max: 3

variables:
  print_status_sensor: !input print_status_sensor
  print_error_binary: !input print_error_binary
  current_stage_sensor: !input current_stage_sensor
  progress_sensor: !input progress_sensor
  printer_name_sensor: !input printer_name_sensor
  task_name_sensor: !input task_name_sensor
  print_weight_sensor: !input print_weight_sensor
  camera_entity: !input camera
  notifications_enabled_boolean: !input notifications_enabled_boolean
  notify_device: !input notify_device
  success_notification_type: !input success_notification_type
  success_critical_start: !input success_critical_start
  success_critical_end: !input success_critical_end
  fault_notification_type: !input fault_notification_type
  fault_critical_start: !input fault_critical_start
  fault_critical_end: !input fault_critical_end
  critical_sound: !input critical_sound
  critical_volume: !input critical_volume
  cooldown_minutes: !input cooldown_minutes
  progress_trigger_threshold: !input progress_trigger_threshold
  printers_view_uri: !input printers_view_uri

  printer_name: "{{ states(printer_name_sensor) }}"
  task_name: "{{ states(task_name_sensor) }}"
  print_weight: "{{ states(print_weight_sensor) }}"
  status: "{{ states(print_status_sensor) }}"
  progress: "{{ states(progress_sensor) | int(0) }}"
  current_stage: "{{ states(current_stage_sensor) }}"
  
  snapshot_file: "/config/www/snapshots/bambu_{{ printer_name | lower | replace(' ', '_') }}.jpg"
  snapshot_url: "/local/snapshots/bambu_{{ printer_name | lower | replace(' ', '_') }}.jpg"

trigger:
  - platform: homeassistant
    event: start
    id: startup

  - platform: event
    event_type: automation_reloaded
    id: reload

  - platform: numeric_state
    id: progress_threshold
    entity_id: !input progress_sensor
    above: !input progress_trigger_threshold

condition:
  - condition: state
    entity_id: !input notifications_enabled_boolean
    state: "on"

  - condition: template
    value_template: >
      {{ not is_state(printer_name_sensor, 'unavailable') and
         not is_state(printer_name_sensor, 'unknown') and
         not is_state(print_status_sensor, 'unavailable') and
         not is_state(print_status_sensor, 'unknown') }}

  - condition: template
    value_template: >
      {% set last = state_attr('automation.' ~ this.object_id, 'last_triggered') %}
      {% if last == none %}
        true
      {% else %}
        {% set last_ts = as_timestamp(last) %}
        {% set diff = as_timestamp(now()) - last_ts %}
        {{ diff > 60 * (cooldown_minutes | int) }}
      {% endif %}

  - condition: template
    value_template: >
      {{ progress > 0 or 
         current_stage in [
           'printing',
           'inspecting_first_layer',
           'auto_bed_leveling',
           'paused'
         ] }}

action:
  # Skip if triggered by startup/reload and printer not in completion state
  - if:
      - condition: template
        value_template: "{{ trigger.id in ['startup', 'reload'] }}"
    then:
      - stop: "Automation reloaded, will trigger at next print completion"

  # Take snapshot immediately (at 99%, bed still up!)
  - service: camera.snapshot
    target:
      entity_id: "{{ camera_entity }}"
    data:
      filename: "{{ snapshot_file }}"
    continue_on_error: true

  # Wait for actual finish/fault state (max 10 minutes)
  - wait_for_trigger:
      - platform: state
        entity_id: !input print_status_sensor
        to:
          - "finish"
          - "failed"
      - platform: state
        entity_id: !input print_error_binary
        to: "on"
    timeout:
      minutes: 10
    continue_on_timeout: false

  - delay: "00:00:02"

  # Calculate notification properties
  - variables:
      is_fault: >
        {{ is_state(print_status_sensor, 'failed') or 
           is_state(print_error_binary, 'on') }}
      is_within_critical_window: >
        {% set now_time = now().time() %}
        {% if is_fault %}
          {% set start = strptime(fault_critical_start, '%H:%M:%S').time() %}
          {% set end = strptime(fault_critical_end, '%H:%M:%S').time() %}
        {% else %}
          {% set start = strptime(success_critical_start, '%H:%M:%S').time() %}
          {% set end = strptime(success_critical_end, '%H:%M:%S').time() %}
        {% endif %}
        {{ now_time >= start and now_time <= end }}
      use_critical_alert: >
        {% if is_fault %}
          {{ fault_notification_type == 'critical' and is_within_critical_window }}
        {% else %}
          {{ success_notification_type == 'critical' and is_within_critical_window }}
        {% endif %}
      notification_title: >
        {% if is_fault %}
          {{ printer_name }} FAULT
        {% else %}
          {{ printer_name }} Print Complete
        {% endif %}
      notification_message: >
        {% if is_fault %}
          ❌ Print Failed
          File: {{ task_name or 'Unknown' }}
          Progress: {{ progress }}%
          Status: {{ status }}
        {% else %}
          ✅ Print Successful
          File: {{ task_name or 'Unknown' }}
          Weight: {{ print_weight }}g
          Progress: {{ progress }}%
        {% endif %}

  # Send mobile notification (if device configured)
  - if:
      - condition: template
        value_template: "{{ notify_device != '' }}"
    then:
      - choose:
          # SUCCESS NOTIFICATION
          - conditions:
              - condition: template
                value_template: "{{ not is_fault }}"
            sequence:
              - service: "notify.{{ notify_device }}"
                data:
                  title: "{{ notification_title }}"
                  message: "{{ notification_message }}"
                  data:
                    image: "{{ snapshot_url }}"
                    tag: "bambu_print_{{ printer_name }}"
                    sticky: false
                    persistent: false
                    push: >
                      {% if use_critical_alert %}
                      {{ {'sound': {'name': critical_sound, 'critical': 1, 'volume': critical_volume}} }}
                      {% endif %}
                    actions: >
                      {% if printers_view_uri != '' %}
                      [{"action": "OPEN_PRINTER_VIEW", "title": "Open printers view", "uri": "{{ printers_view_uri }}"}]
                      {% else %}
                      []
                      {% endif %}

          # FAULT NOTIFICATION
          - conditions:
              - condition: template
                value_template: "{{ is_fault }}"
            sequence:
              - service: "notify.{{ notify_device }}"
                data:
                  title: "{{ notification_title }}"
                  message: "{{ notification_message }}"
                  data:
                    image: "{{ snapshot_url }}"
                    tag: "bambu_print_{{ printer_name }}"
                    sticky: true
                    persistent: true
                    push: >
                      {% if use_critical_alert %}
                      {{ {'sound': {'name': critical_sound, 'critical': 1, 'volume': critical_volume}} }}
                      {% endif %}
                    actions: >
                      {% if printers_view_uri != '' %}
                      [{"action": "OPEN_PRINTER_VIEW", "title": "Open printers view", "uri": "{{ printers_view_uri }}"}]
                      {% else %}
                      []
                      {% endif %}

  # Create persistent notification for faults only
  - if:
      - condition: template
        value_template: "{{ is_fault }}"
    then:
      - service: persistent_notification.create
        data:
          title: "{{ printer_name }} fault"
          message: >
            {{ task_name or 'Print job' }} on {{ printer_name }} has a fault.
            Status: {{ status }}, progress {{ progress }}%.
          notification_id: "bambu_fault_{{ printer_name }}"
